general:
  config_path: ../../configs
  data_path: ../../data/
  data_raw_path: ../../data/raw/
  model_name: digit82/kobart-summarization
  output_dir: ../../outputs/checkpoints/
  output_path: ../../outputs/
  version: v2
inference:
  batch_size: 32
  ckt_path: ../../outputs/checkpoints/
  early_stopping: true
  generate_max_length: 100
  length_penalty: 1.1
  max_length: 100
  no_repeat_ngram_size: 2
  num_beams: 4
  remove_tokens:
  - <usr>
  - <s>
  - </s>
  - <pad>
  repetition_penalty: 1.0
  result_path: ../../outputs/prediction/
tokenizer:
  bos_token: <s>
  decoder_max_len: 100
  encoder_max_len: 512
  eos_token: </s>
  special_tokens:
  - '#Person1#'
  - '#Person2#'
  - '#Person3#'
  - '#PhoneNumber#'
  - '#Address#'
  - '#PassportNumber#'
training:
  do_eval: true
  do_train: true
  early_stopping_patience: 3
  early_stopping_threshold: 0.001
  evaluation_strategy: epoch
  fp16: true
  generation_max_length: 100
  gradient_accumulation_steps: 1
  greater_is_better: true
  label_smoothing_factor: 0.1
  learning_rate: 1.0e-05
  load_best_model_at_end: true
  logging_dir: ./logs
  logging_strategy: epoch
  lr_scheduler_type: cosine
  max_grad_norm: 1.0
  metric_for_best_model: eval_rouge_l
  num_train_epochs: 20
  optim: adamw_torch
  overwrite_output_dir: true
  per_device_eval_batch_size: 32
  per_device_train_batch_size: 50
  predict_with_generate: true
  report_to: wandb
  save_strategy: epoch
  save_total_limit: 5
  seed: 99
  warmup_ratio: 0.1
  weight_decay: 0.01
wandb:
  name: preprocessed_v2_input_only_seed_99
  project: NLP-private
